{% set name = "PyQtWebEngine" %}
{% set version = "5.15.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}{{ version[0] }}/{{ name }}{{ version[0] }}-{{ version }}.tar.gz
  sha256: cedc28f54165f4b8067652145aec7f732a17eadf6736835852868cf76119cc19

build:
  number: 0
  # script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-libgl') }}  # [linux]
    - {{ cdt('mesa-libegl') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
    - {{ cdt('alsa-lib-devel') }}    # [linux]
    - {{ cdt('cups-devel') }}    # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('alsa-lib-devel') }}        # [linux]
    - {{ cdt('gtk2-devel') }}            # [linux]
    - {{ cdt('gtkmm24-devel') }}         # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxxf86vm-devel') }}      # [linux]
    - {{ cdt('cups-devel') }}            # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('expat-devel') }}           # [linux]
    - {{ cdt('pcre') }}                  # [linux]
  host:
    - python >=3.6
    - pip
    - sip >=6.1.0
    - pyqt-builder >=1.10.0
    - toml
    - packaging
    - qt >=5.15.2
    - qtwebengine
    - pyqt >=5.15.4
  run:
    - python >=3.6
    - qt >=5.15.2
    - pyqt >=5.15.4
    - qtwebengine
    - pyqt5-sip

test:
  imports:
    - PyQt5
    # - simplejson.tests
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://www.riverbankcomputing.com/software/pyqtwebengine/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'Python bindings for the Qt WebEngine framework'
  # The remaining entries in this section are optional, but recommended.
  description: |
    PyQtWebEngine is a set of Python bindings for The Qt Company’s Qt WebEngine
    framework. The framework provides the ability to embed web content in
    applications and is based on the Chrome browser. The bindings sit on top
    of PyQt5 and are implemented as three separate modules corresponding to
    the different libraries that make up the framework.
  doc_url: https://www.riverbankcomputing.com/static/Docs/PyQt5/
  dev_url: https://www.riverbankcomputing.com/mailman/listinfo/pyqt/

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - LisaSimpson
    - LandoCalrissian
