{% set name = "qt" %}
{% set version = "5.15.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://download.qt.io/official_releases/qt/{{ version.rpartition('.')[0] }}/{{ version }}/single/qt-everywhere-src-{{ version }}.tar.xz
  sha256: 3a530d1b243b5dec00bc54937455471aaa3e56849d2593edb8ded07228202240

build:
  number: 2

requirements:
  build:
    # If your project compiles code (such as a C extension) then add the required compilers as separate entries here.
    # Compilers are named 'c', 'cxx' and 'fortran'.
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
    - {{ cdt('alsa-lib-devel') }}    # [linux]
    - {{ cdt('cups-devel') }}    # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('alsa-lib-devel') }}        # [linux]
    - {{ cdt('gtk2-devel') }}            # [linux]
    - {{ cdt('gtkmm24-devel') }}         # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxcomposite-devel') }}   # [linux]
    - {{ cdt('libxcursor-devel') }}      # [linux]
    - {{ cdt('libxi-devel') }}           # [linux]
    - {{ cdt('libxrandr-devel') }}       # [linux]
    - {{ cdt('pciutils-devel') }}        # [linux]
    - {{ cdt('libxscrnsaver-devel') }}   # [linux]
    - {{ cdt('libxtst-devel') }}         # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxxf86vm-devel') }}      # [linux]
    - {{ cdt('cups-devel') }}            # [linux]
    - {{ cdt('libxcb') }}                # [linux]
    - {{ cdt('expat-devel') }}           # [linux]
    # - {{ cdt('pcre') }}                  # [linux and cdt_name != 'cos6']
    # - {{ cdt('libglvnd-glx') }}          # [linux and cdt_name != 'cos6']
    - pkg-config                         # [unix]
    - make                               # [unix]
    - cmake
    - ninja
    - ruby >=2.5                         # [linux]
    - bison                              # [linux]
    - flex                               # [linux]
    - gperf                              # [linux]
    - perl 5.*
    - readline                           # [linux]
  host:
    - gtk3
    # - libpng
    - libjpeg-turbo
    - pulseaudio
    - gstreamer
    - pthread-stubs                      # [linux]
    - dbus                               # [linux]
    - fontconfig                         # [linux]
    - freetype                           # [linux]
    - gst-plugins-base                   # [linux]
    - gstreamer                          # [linux]
    - libglib                            # [linux]
    - libxml2                            # [linux]
    - libxkbcommon                       # [linux]
    - expat                              # [linux]
    - libevent                           # [linux]
    - icu
    # - jpeg
    - libpng
    - libiconv
    - nspr                               # [unix]
    - nss                                # [unix]
    - sqlite
    - mysql-devel                        # [not win]
    - postgresql                         # [not win]
    - zlib
    - libxcb                             # [linux]
  run:
    - gtk3
    - libpng
    - libjpeg-turbo
    - pulseaudio
    - gstreamer

# test:
#   # Some packages might need a `test/commands` key to check CLI.
#   # List all the packages/modules that `run_test.py` imports.
#   imports:
#     - simplejson
#     - simplejson.tests
#   # For python packages, it is useful to run pip check. However, sometimes the
#   # metadata used by pip is out of date. Thus this section is optional if it is
#   # failing.
#   requires:
#     - pip
#   commands:
#     - pip check

about:
  home: http://qt.io
  license: LGPL-3.0-only
  license_file: LICENSE.LGPLv3
  summary: 'Qt is a cross-platform application and UI framework.'
  description: |
    Qt helps you create connected devices, UIs & applications that run
    anywhere on any device, on any operating system at any time.
  doc_url: http://doc.qt.io/
  dev_url: https://github.com/qt

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - LisaSimpson
    - LandoCalrissian
