cdt_name: cos7
c_compiler:  # [win]
- vs2019  # [win]
cxx_compiler:  # [win]
- vs2019  # [win]
c_compiler_version: # [win]
  - 19.28                    # [win]
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - '10.13'                # [osx and x86_64]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - '10.14'                # [osx and x86_64]
